testname: Podcast Evaluation Questionnaire 
testId: questionnaire
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php



pages: 
    - type: generic
      id: first_page
      name: Welcome to the <span class="highlight">Podcast Evaluation Questionnaire</span>!
      content: <p></p>
        <span class="content-header">Study Description:</span> 
        <p>In this study, we aim to collect <span class="highlight">authentic feedback</span> on podcast audio clips. You will listen to <span class="highlight">4 different podcast audio files</span>, each discussing potentially different topics. The primary goal of this research is to evaluate the <span class="highlight">overall production quality</span> of the podcast segments, rather than the specific content or themes being discussed.</p>

        <p>Each audio clip is approximately <span class="highlight">3 minutes long</span> and is constructed by combining three key segments from a full podcast episode:</p>
        <p>&lt;The <span class="highlight">first</span> minute | The <span class="highlight">middle</span> minute | The <span class="highlight">final</span> minute&gt;</p>
        <p>A brief notification sound will indicate the transitions between these segments.</p>

        <p></p>
        <span class="content-header">About the questionnaire:</span>
        <p>It consists of two sections:</p>
        <ol>
          <li><span class="highlight">Quantitative Analysis (7 questions)</span>: Rate each aspect on a scale of <span class="highlight">0 to 10</span> (where <span class="highlight">0</span> = Not Met At All, <span class="highlight">5</span> = Moderately Met, <span class="highlight">10</span> = Fully Met).</li>
          <li><span class="highlight">Qualitative Analysis (3 questions)</span>: Provide additional feedback by answering <span class="highlight">YES/NO/CAN’T TELL</span> questions. Comments are optional but highly encouraged.</li>
        </ol>
        <p>This questionnaire is designed to assess the podcast’s production quality across multiple dimensions, such as:</p>
        <ul>
          <li>The appropriateness of the speaker’s voice and tone.</li>
          <li>The clarity and expressiveness of the speech delivery.</li>
          <li>The overall appeal and engagement of the podcast.</li>
          <li>The suitability of background music or sound effects.</li>
          <li>The audio quality (e.g., clarity, balance).</li>
        </ul>
        <p>We kindly ask you to <span class="highlight">avoid rating based on the discussion topic itself</span> and instead focus on the <span class="highlight">overall performance</span> of the audio.</p>
        <p>Please <span class="highlight">listen to each audio carefully</span>, ideally using <span class="highlight">headphones</span> for optimal clarity.</p>
        <p><span class="highlight">Incomplete or insincere responses may be subject to return.</span> We kindly ask you to provide thoughtful and genuine feedback to ensure the effectiveness of this study.</p>
        <p>Your feedback is <span class="highlight">extremely valuable</span>. Thank you for your participation!</p>
        
        
          
    - type: likert_single_stimulus
      id: System1
      name: System
      content:  
      showWaveform: true
      mustRate: true
      randomize: true
      maxStimuli: 4
      stimuli:
          Social_mossttsd: configs/resources/audio/mos_samples/mossttsd/Society_and_Culture_1.wav
          Social_notebooklm: configs/resources/audio/mos_samples/notebooklm/Society_and_Culture_2.wav
          Social_podagent: configs/resources/audio/mos_samples/podagent/Society_and_Culture_2.wav
          Social_realpod: configs/resources/audio/mos_samples/realpod/Society_and_Culture_2.wav
      response:
        -
          - value: 
            label: How many speakers are there in the podcast?
            type: option
        - 
          - value: 
            title: Section 1: Quantitative Analysis (0-10 Scale)
            description: <span class="highlight">0</span> = not met at all, <span class="highlight">5</span> = moderately met, <span class="highlight">10</span> = fully met. Comments are optional but encouraged.
            label: 1.  How well does the tone of the host or guest suit the podcast content?
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            label: 2. How clearly and effectively do the speakers deliver the podcast content?
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            label: 3. Is the speaking pace appropriate and easy to follow?
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            label: 4. How engaging and enjoyable is the podcast? (Does it sustain your attention throughout the episode?)
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        - 
          - value: 
            label: 5. How satisfied are you with the podcast's audio quality? (e.g., clarity, background noise)
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        - 
          - value: 
            label: 6. If background music or sound effects are present, how well do they enhance rather than interfere with the content? (Select 5 if there is no background music or sound effects)
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        - 
          - value: 
            label: 7. How likely are you to want to listen to the full episode after hearing this excerpt?
            type: rate
            rate: 11
            min_value: not met at all
            mid_value: moderately met
            max_value: fully met
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            title: Section 2: Qualitative Analysis (YES/NO/CAN’T TELL)
            label: 8. Does the podcast include a clear introduction and conclusion?
            type: select
            select_value: YES/NO/CAN’T TELL
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            label: 9. Are background music or sound effects present in the podcast?
            type: select
            select_value: YES/NO/CAN’T TELL
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            label: 10. Does the podcast sound like it was created by humans rather than AI?（"Yes" = more like humans, "No" = more like AI）
            type: select
            select_value: YES/NO/CAN’T TELL
            img: configs/resources/images/star_off.png
            imgSelected: configs/resources/images/star_on.png
            imgHigherResponseSelected: configs/resources/images/star_on.png
        -
          - value: 
            title: Additional Comments (Optional)
            label: 11. Any additional comments on this podcast audio?
            type: option

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: Username
            name: username
          - type: likert
            name: gender
            label: Gender
            response:
              - type: select
                select_value: Female/Male/Other
          - type: likert
            name: Age
            label: Age
            response:
              - type: select
                select_value: <20/20-40/40-60/>60
          - type: likert
            name: ebackground
            label: Education Background
            response:
               - type: select
                 select_value: Less than high school/High school or equivalent/Bachelor’s degree/Master’s degree/Doctorate or higher
          - type: likert
            label: Have you ever created a podcast before?
            name: createPodcast
            response:
               - type: select
                 select_value: Yes/No
          - type: likert
            label: Have you listened to podcasts before?
            name: listenPodcast
            response:
               - type: select
                 select_value: Yes/No
          - type: likert2
            name: typePodcasts 
            optional: true
            label: If yes, what types of podcasts do you listen to? (Select all that apply) 
            response:
             - value: Society and Culture
               label: Society and Culture
             - value: Comedy
               label: Comedy
             - value: News
               label: News
             - value: Education
               label: Education
             - value: Business
               label: Business
             - value: Health and fitness 
               label: Health and fitness
             - value: Arts
               label: Arts
             - value: Music
               label: Music
             - value: Sports
               label: Sports
             - value: Science and Technology
               label: Science and Technology
             - value: History
               label: History
             - value: True Crime
               label: True Crime
             - value: Kids and family
               label: Kids and family
             - value: TV and Film
               label: TV and Film
             - value: Leisure
               label: Leisure
             - value: Fiction
               label: Fiction
             - value: Mental health
               label: Mental health
             - value: Other
               label: Other:<input id="other"></input>